### ISSUE TITLE
[BUG] docker compose command not deploying configuration therefore breaking haproxy

### ISSUE THREAD

**Issue by Masber** [OpenCHAMI/deployment-recipes#102]
**Describe the bug**
Following "quickstart" instructions:

when running command:

`docker compose -f base.yml -f postgres.yml -f jwt-security.yml -f haproxy-api-gateway.yml -f  openchami-svcs.yml -f autocert.yml -f coredhcp.yml up -d`

haproxy container fails and logs will show:

```
[NOTICE]   (1) : haproxy version is 2.9.9
[NOTICE]   (1) : path to executable is /usr/sbin/haproxy
[ALERT]    (1) : config : [/usr/local/etc/haproxy/haproxy.cfg:72] : 'server configurator/configurator' : could not resolve address 'configurator'.
[ALERT]    (1) : config : Failed to initialize server(s) addr.
```

**To Reproduce**
1. Follow quickstart instructions
2. Run docker compose command
3. Check docker containers and see if haproxy is up
4. Check haproxy container logs

**Expected behavior**

After running docker compose, all container should run

**Screenshots**

**Desktop (please complete the following information):**
 - OS: macos sequoia

**Additional context**

To solve this I had to add the configurator.yaml file to the docker compose command like below:

`docker compose -f base.yml -f postgres.yml -f jwt-security.yml -f haproxy-api-gateway.yml -f  openchami-svcs.yml -f autocert.yml -f coredhcp.yml -f configurator.yml up -d`

**Comment by synackd** [comment]
Ah, just looks like `configurator.yml` needs to be added to the command line in the instructions, which the PR linked above does.
