### ISSUE TITLE
Step 5 of Quickstart Guide: Curl Command Should Curl on Port 8443

### ISSUE THREAD

**Issue by alanakihn** [OpenCHAMI/deployment-recipes#64]
Oh the final command of **Step 5 of the Quickstart Guide** -

`curl --cacert cacert.pem -H "Authorization: Bearer $ACCESS_TOKEN" https://foobar.openchami.cluster/hsm/v2/State/Components`

results in a `Connection refused error`.

The port should be 8443 by default.

Corrected command:

`curl --cacert cacert.pem -H "Authorization: Bearer $ACCESS_TOKEN" https://foobar.openchami.cluster:8443/hsm/v2/State/Components`

**Comment by synackd** [comment]
This is addressed in the quickstart README in #66.
